'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export function AuthForm({ mode }: { mode: 'login' | 'signup' }) {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const supabase = createClient(); const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { full_name: fullName }, emailRedirectTo: `${window.location.origin}/auth/callback` } }); setBusy(false); if (result.error) { setMessage(mode === 'login' ? 'Invalid email or password.' : 'Unable to create account. Check your details and try again.'); return } if (mode === 'signup' && !result.data.session) { setMessage('Check your email to confirm your warehouse member account.'); return } router.push('/fulfillment'); router.refresh() }
  return <form className="auth-card" onSubmit={submit}><p className="eyebrow">NORTHSTAR · RF SCANNER</p><h1>{mode === 'login' ? 'Member sign in' : 'Create member access'}</h1><p className="auth-copy">{mode === 'login' ? 'Sign in to use the warehouse RF scanner.' : 'Create an email and password account for a warehouse member.'}</p>{mode === 'signup' && <label>Full name<input required value={fullName} onChange={(e) => setFullName(e.target.value)} /></label>}<label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button disabled={busy}>{busy ? 'Working…' : mode === 'login' ? 'Sign in' : 'Create account'}</button>{message && <p className="auth-message">{message}</p>}<a href={mode === 'login' ? '/auth/sign-up' : '/auth/login'}>{mode === 'login' ? 'Create a member account' : 'Already have an account? Sign in'}</a></form>
}
